"""Convert word_cards.xlsx -> word_cards.json + word_cards.js (browser-loadable).

Usage:
    python word_card_to_json.py [folder]

`folder` defaults to the current directory. The folder must contain
`word_cards.xlsx`. Outputs go into the same folder.

word_cards.xlsx format
---------------------
Row 1: header — German | IPA | English meaning | Example | 中文释义（整句翻译）
Row 2+: data. IPA column may be empty (auto-generated by rule-based transcriber).

If a word appears in multiple rows, examples are merged.

Audio paths are computed deterministically:
  - word audio    : audio/words/<slug>.mp3       (slug = lowercased letters only)
  - example audio : audio/examples/<hash>.mp3    (hash = sha1(de_text.lower())[:12])

Run `generate_card_audio.py <folder>` to generate missing audio first.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

import openpyxl


def slug(word: str) -> str:
    s = word.lower().strip()
    s = re.sub(r"[^a-zäöüß\-]", "", s)
    return s


def example_hash(text: str) -> str:
    return hashlib.sha1(text.lower().encode("utf-8")).hexdigest()[:12]


# ===== German IPA transcriber (rule-based, approximate) =====
_IPA_MULTI = [
    ("tsch", "tʃ"), ("sch", "ʃ"), ("ck", "k"), ("ph", "f"), ("qu", "kv"),
    ("ie", "iː"), ("ei", "aɪ"), ("ai", "aɪ"), ("ey", "aɪ"), ("ay", "aɪ"),
    ("eu", "ɔɪ"), ("äu", "ɔɪ"), ("au", "aʊ"),
    ("oo", "oː"), ("ee", "eː"), ("aa", "aː"),
    ("ß", "s"), ("ch", "ç"),
]
_IPA_SINGLE = {
    "a":"a","e":"e","i":"ɪ","o":"o","u":"u",
    "ä":"ɛ","ö":"øː","ü":"yː",
    "b":"b","d":"d","f":"f","g":"ɡ","h":"h",
    "j":"j","k":"k","l":"l","m":"m","n":"n",
    "p":"p","r":"ʁ","s":"z","t":"t",
    "v":"f","w":"v","x":"ks","y":"yː","z":"ts","q":"k",
}
_IPA_BACK = {"a", "aː", "o", "oː", "u", "uː", "aʊ"}


def de_to_ipa(word: str) -> str:
    s = re.sub(r"[^a-zäöüß]+$", "", word.lower())
    s = re.sub(r"^[^a-zäöüß]+", "", s)
    if not s:
        return ""
    out: list[str] = []
    i = 0
    while i < len(s):
        if i == 0 and s[:2] == "st":
            out.append("ʃt"); i += 2; continue
        if i == 0 and s[:2] == "sp":
            out.append("ʃp"); i += 2; continue
        matched = False
        for pat, ipa in _IPA_MULTI:
            if s[i:i + len(pat)] == pat:
                if pat == "ch" and out and out[-1] in _IPA_BACK:
                    out.append("x")
                else:
                    out.append(ipa)
                i += len(pat); matched = True; break
        if matched:
            continue
        c = s[i]
        if c in _IPA_SINGLE:
            out.append(_IPA_SINGLE[c])
        i += 1
    res = "".join(out)
    res = re.sub(r"ʁ$", "ɐ", res)
    res = re.sub(r"ɡ$", "k", res)
    res = re.sub(r"b$", "p", res)
    res = re.sub(r"d$", "t", res)
    return "ˈ" + res if res else res


def parse_ipa_cell(value: str) -> str:
    """Strip surrounding slashes/brackets from an IPA cell."""
    if not value:
        return ""
    s = value.strip()
    # Remove surrounding /.../ or [...]
    if (s.startswith("/") and s.endswith("/")) or (s.startswith("[") and s.endswith("]")):
        s = s[1:-1].strip()
    return s


def parse_xlsx(path: Path):
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    ws = wb.active
    cards: dict[str, dict] = {}
    order: list[str] = []
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        cells = [str(c).strip() if c is not None else "" for c in row]
        if i == 0:
            # header — skip
            continue
        # Pad to at least 5 cells
        while len(cells) < 5:
            cells.append("")
        word, ipa_raw, en, ex_de, ex_zh = cells[:5]
        if not word:
            continue
        ipa = parse_ipa_cell(ipa_raw)
        key = word.lower()
        if key not in cards:
            cards[key] = {
                "word": word,
                "ipa_override": ipa,
                "en": en,
                "examples": [],
            }
            order.append(key)
        else:
            if ipa and not cards[key]["ipa_override"]:
                cards[key]["ipa_override"] = ipa
            if en and not cards[key]["en"]:
                cards[key]["en"] = en
            if word[:1].isupper() and not cards[key]["word"][:1].isupper():
                cards[key]["word"] = word
        if ex_de and not any(e["de"] == ex_de for e in cards[key]["examples"]):
            cards[key]["examples"].append({"de": ex_de, "zh": ex_zh})
    return [cards[k] for k in order]


def main():
    folder = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
    xlsx = folder / "word_cards.xlsx"
    if not xlsx.exists():
        print(f"[error] {xlsx} not found.", file=sys.stderr)
        sys.exit(1)

    parsed = parse_xlsx(xlsx)
    print(f"[info] {folder.name}: parsed {len(parsed)} cards")

    cards = {}
    missing_word_audio = []
    missing_ex_audio = []
    for c in parsed:
        key = slug(c["word"])
        if not key:
            continue
        word_audio = f"audio/words/{key}.mp3"
        if not (folder / "audio" / "words" / f"{key}.mp3").exists():
            missing_word_audio.append(c["word"])
        examples = []
        for ex in c["examples"]:
            eh = example_hash(ex["de"])
            ex_audio = f"audio/examples/{eh}.mp3"
            if not (folder / "audio" / "examples" / f"{eh}.mp3").exists():
                missing_ex_audio.append(ex["de"])
            examples.append({"de": ex["de"], "zh": ex["zh"], "audio": ex_audio})
        ipa = c.get("ipa_override", "") or de_to_ipa(c["word"])
        cards[key] = {
            "word": c["word"],
            "ipa": ipa,
            "en": c["en"],
            "examples": examples,
            "audio": word_audio,
        }

    out_json = folder / "word_cards.json"
    out_js = folder / "word_cards.js"
    out_json.write_text(json.dumps(cards, ensure_ascii=False, indent=2), encoding="utf-8")
    out_js.write_text(
        "// AUTO-GENERATED from word_cards.xlsx by word_card_to_json.py — do not edit.\n"
        "// Edit word_cards.xlsx, then run: python generate_card_audio.py <folder> && python word_card_to_json.py <folder>\n"
        "window.WORD_CARDS = " + json.dumps(cards, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"[done] {folder.name}: wrote {out_json.name} ({out_json.stat().st_size} B), {out_js.name} ({out_js.stat().st_size} B)")
    empty_en = sum(1 for c in cards.values() if not c["en"])
    if empty_en:
        print(f"[info] {empty_en} card(s) with empty English meaning")
    if missing_word_audio:
        print(f"[warn] {len(missing_word_audio)} word(s) missing audio")
    if missing_ex_audio:
        print(f"[warn] {len(missing_ex_audio)} example(s) missing audio")


if __name__ == "__main__":
    main()
