// AUTO-GENERATED by generate_tts.py — do not edit.
// Regenerate by running: python generate_tts.py <folder>
window.TTS_INDEX = {
  "voice": "de-DE-KatjaNeural",
  "rate": "-10%",
  "words": {
    "Regen": "audio/words/regen.mp3",
    "vorbei": "audio/words/vorbei.mp3",
    "Lichter": "audio/words/lichter.mp3",
    "wach": "audio/words/wach.mp3",
    "Ein": "audio/words/ein.mp3",
    "kaltes": "audio/words/kaltes.mp3",
    "Aichen": "audio/words/aichen.mp3",
    "in": "audio/words/in.mp3",
    "meiner": "audio/words/meiner.mp3",
    "Hand": "audio/words/hand.mp3",
    "Komm": "audio/words/komm.mp3",
    "Nicht": "audio/words/nicht.mp3",
    "zurück": "audio/words/zurück.mp3",
    "die": "audio/words/die.mp3",
    "Nacht": "audio/words/nacht.mp3",
    "Ich": "audio/words/ich.mp3",
    "legte": "audio/words/legte.mp3",
    "den": "audio/words/den.mp3",
    "Kasten": "audio/words/kasten.mp3",
    "auf": "audio/words/auf.mp3",
    "Tisch": "audio/words/tisch.mp3",
    "dachte": "audio/words/dachte.mp3",
    "jetzt": "audio/words/jetzt.mp3",
    "wird": "audio/words/wird.mp3",
    "alles": "audio/words/alles.mp3",
    "leicht": "audio/words/leicht.mp3",
    "Schuld": "audio/words/schuld.mp3",
    "bekommt": "audio/words/bekommt.mp3",
    "Ende": "audio/words/ende.mp3",
    "wenn": "audio/words/wenn.mp3",
    "man": "audio/words/man.mp3",
    "sie": "audio/words/sie.mp3",
    "endlich": "audio/words/endlich.mp3",
    "leise": "audio/words/leise.mp3",
    "Aigt": "audio/words/aigt.mp3",
    "Doch": "audio/words/doch.mp3",
    "morgens": "audio/words/morgens.mp3",
    "war": "audio/words/war.mp3",
    "das": "audio/words/das.mp3",
    "Zimmer": "audio/words/zimmer.mp3",
    "leer": "audio/words/leer.mp3",
    "Der": "audio/words/der.mp3",
    "Schrank": "audio/words/schrank.mp3",
    "offen": "audio/words/offen.mp3",
    "kalt": "audio/words/kalt.mp3",
    "und": "audio/words/und.mp3",
    "weiß": "audio/words/weiß.mp3",
    "kam": "audio/words/kam.mp3",
    "zu": "audio/words/zu.mp3",
    "spät": "audio/words/spät.mp3",
    "Reue": "audio/words/reue.mp3",
    "hat": "audio/words/hat.mp3",
    "keinen": "audio/words/keinen.mp3",
    "Preis": "audio/words/preis.mp3",
    "wollte": "audio/words/wollte.mp3",
    "heilen": "audio/words/heilen.mp3",
    "was": "audio/words/was.mp3",
    "brach": "audio/words/brach.mp3",
    "zahlen": "audio/words/zahlen.mp3",
    "nahm": "audio/words/nahm.mp3",
    "jeder": "audio/words/jeder.mp3",
    "Schritt": "audio/words/schritt.mp3",
    "nach": "audio/words/nach.mp3",
    "Hause": "audio/words/hause.mp3",
    "zündet": "audio/words/zündet.mp3",
    "eine": "audio/words/eine.mp3",
    "neue": "audio/words/neue.mp3",
    "Flamme": "audio/words/flamme.mp3",
    "an": "audio/words/an.mp3",
    "gab": "audio/words/gab.mp3",
    "es": "audio/words/es.mp3",
    "nichts": "audio/words/nichts.mp3",
    "Grab": "audio/words/grab.mp3",
    "Blick": "audio/words/blick.mp3",
    "stummer": "audio/words/stummer.mp3",
    "Fluch": "audio/words/fluch.mp3",
    "Faden": "audio/words/faden.mp3",
    "schneidet": "audio/words/schneidet.mp3",
    "meine": "audio/words/meine.mp3",
    "Er": "audio/words/er.mp3",
    "führt": "audio/words/führt.mp3",
    "mich": "audio/words/mich.mp3",
    "langsam": "audio/words/langsam.mp3",
    "durch": "audio/words/durch.mp3",
    "Stadt": "audio/words/stadt.mp3",
    "suche": "audio/words/suche.mp3",
    "dich": "audio/words/dich.mp3",
    "weil": "audio/words/weil.mp3",
    "fällt": "audio/words/fällt.mp3",
    "mehr": "audio/words/mehr.mp3",
    "hält": "audio/words/hält.mp3",
    "Du": "audio/words/du.mp3",
    "findest": "audio/words/findest.mp3",
    "dieser": "audio/words/dieser.mp3",
    "hellen": "audio/words/hellen.mp3",
    "Dunkelheit": "audio/words/dunkelheit.mp3",
    "mir": "audio/words/mir.mp3",
    "kein": "audio/words/kein.mp3",
    "Weg": "audio/words/weg.mp3",
    "bleibt": "audio/words/bleibt.mp3",
    "hör": "audio/words/hör.mp3",
    "dein": "audio/words/dein.mp3",
    "Herz": "audio/words/herz.mp3",
    "kenn": "audio/words/kenn.mp3",
    "Schmerz": "audio/words/schmerz.mp3",
    "Nachtserenade": "audio/words/nachtserenade.mp3",
    "zieh": "audio/words/zieh.mp3",
    "mit": "audio/words/mit.mp3",
    "Wir": "audio/words/wir.mp3",
    "tanAn": "audio/words/tanan.mp3",
    "wo": "audio/words/wo.mp3",
    "Arbricht": "audio/words/arbricht.mp3",
    "finde": "audio/words/finde.mp3",
    "Morgen": "audio/words/morgen.mp3",
    "wäscht": "audio/words/wäscht.mp3",
    "uns": "audio/words/uns.mp3",
    "wieder": "audio/words/wieder.mp3",
    "rein": "audio/words/rein.mp3",
    "sind": "audio/words/sind.mp3",
    "um": "audio/words/um.mp3",
    "frei": "audio/words/frei.mp3",
    "sein": "audio/words/sein.mp3",
    "biss": "audio/words/biss.mp3",
    "Lachen": "audio/words/lachen.mp3",
    "Mund": "audio/words/mund.mp3",
    "hier": "audio/words/hier.mp3",
    "vor": "audio/words/vor.mp3",
    "ihnen": "audio/words/ihnen.mp3",
    "schlägt": "audio/words/schlägt.mp3",
    "meinen": "audio/words/meinen.mp3",
    "Rippen": "audio/words/rippen.mp3",
    "so": "audio/words/so.mp3",
    "süß": "audio/words/süß.mp3",
    "nah": "audio/words/nah.mp3",
    "bei": "audio/words/bei.mp3",
    "hielt": "audio/words/hielt.mp3",
    "ihn": "audio/words/ihn.mp3",
    "fest": "audio/words/fest.mp3",
    "wie": "audio/words/wie.mp3",
    "neues": "audio/words/neues.mp3",
    "blieb": "audio/words/blieb.mp3",
    "stumm": "audio/words/stumm.mp3",
    "verschlossen": "audio/words/verschlossen.mp3",
    "jage": "audio/words/jage.mp3",
    "warte": "audio/words/warte.mp3",
    "nur": "audio/words/nur.mp3",
    "zähle": "audio/words/zähle.mp3",
    "deine": "audio/words/deine.mp3",
    "Schritte": "audio/words/schritte.mp3",
    "kommst": "audio/words/kommst.mp3",
    "Spur": "audio/words/spur.mp3",
    "nennst": "audio/words/nennst.mp3",
    "Wahrheit": "audio/words/wahrheit.mp3",
    "Pflicht": "audio/words/pflicht.mp3",
    "bist": "audio/words/bist.mp3",
    "Licht": "audio/words/licht.mp3",
    "Trost": "audio/words/trost.mp3",
    "Schlüssel": "audio/words/schlüssel.mp3",
    "Wunde": "audio/words/wunde.mp3",
    "lächle": "audio/words/lächle.mp3",
    "Noch": "audio/words/noch.mp3",
    "halte": "audio/words/halte.mp3",
    "still": "audio/words/still.mp3",
    "lasse": "audio/words/lasse.mp3",
    "kommen": "audio/words/kommen.mp3",
    "musst": "audio/words/musst.mp3",
    "Fehler": "audio/words/fehler.mp3",
    "trägt": "audio/words/trägt.mp3",
    "mein": "audio/words/mein.mp3",
    "Atem": "audio/words/atem.mp3",
    "hängt": "audio/words/hängt.mp3",
    "Luft": "audio/words/luft.mp3",
    "bin": "audio/words/bin.mp3",
    "erkennt": "audio/words/erkennt.mp3",
    "Tür": "audio/words/tür.mp3",
    "für": "audio/words/für.mp3",
    "brennt": "audio/words/brennt.mp3",
    "schließt": "audio/words/schließt.mp3",
    "gut": "audio/words/gut.mp3",
    "machen": "audio/words/machen.mp3",
    "wolltest": "audio/words/wolltest.mp3",
    "kamst": "audio/words/kamst.mp3",
    "Falle": "audio/words/falle.mp3",
    "Sag": "audio/words/sag.mp3",
    "ob": "audio/words/ob.mp3",
    "etwas": "audio/words/etwas.mp3",
    "Bleib": "audio/words/bleib.mp3",
    "von": "audio/words/von.mp3",
    "dir": "audio/words/dir.mp3",
    "habe": "audio/words/habe.mp3",
    "zweimal": "audio/words/zweimal.mp3",
    "verloren": "audio/words/verloren.mp3",
    "Dann": "audio/words/dann.mp3",
    "gebe": "audio/words/gebe.mp3",
    "einen": "audio/words/einen.mp3",
    "Grund": "audio/words/grund.mp3",
    "halten": "audio/words/halten.mp3",
    "suchen": "audio/words/suchen.mp3",
    "Ausgang": "audio/words/ausgang.mp3",
    "singt": "audio/words/singt.mp3",
    "finden": "audio/words/finden.mp3",
    "schönen": "audio/words/schönen.mp3",
    "führst": "audio/words/führst.mp3",
    "tief": "audio/words/tief.mp3",
    "bis": "audio/words/bis.mp3",
    "keiner": "audio/words/keiner.mp3",
    "seinen": "audio/words/seinen.mp3",
    "Namen": "audio/words/namen.mp3",
    "ist": "audio/words/ist.mp3",
    "laut": "audio/words/laut.mp3",
    "schaut": "audio/words/schaut.mp3",
    "brenn": "audio/words/brenn.mp3",
    "allein": "audio/words/allein.mp3",
    "macht": "audio/words/macht.mp3",
    "binden": "audio/words/binden.mp3",
    "letzter": "audio/words/letzter.mp3",
    "deiner": "audio/words/deiner.mp3"
  },
  "sentences": [
    {
      "id": "0-0",
      "file": "audio/sentences/00_00.mp3",
      "de": "Regen vorbei.",
      "zh": "雨已停歇。"
    },
    {
      "id": "0-1",
      "file": "audio/sentences/00_01.mp3",
      "de": "Lichter wach.",
      "zh": "灯火未眠。"
    },
    {
      "id": "0-2",
      "file": "audio/sentences/00_02.mp3",
      "de": "Ein kaltes Aichen",
      "zh": "一枚冰冷印记"
    },
    {
      "id": "0-3",
      "file": "audio/sentences/00_03.mp3",
      "de": "in meiner Hand.",
      "zh": "攥在我掌间。"
    },
    {
      "id": "0-4",
      "file": "audio/sentences/00_04.mp3",
      "de": "Komm, komm.",
      "zh": "来吧，来吧。"
    },
    {
      "id": "0-5",
      "file": "audio/sentences/00_05.mp3",
      "de": "Nicht zurück.",
      "zh": "别再回头。"
    },
    {
      "id": "0-6",
      "file": "audio/sentences/00_06.mp3",
      "de": "Komm, komm.",
      "zh": "来吧，来吧。"
    },
    {
      "id": "0-7",
      "file": "audio/sentences/00_07.mp3",
      "de": "In die Nacht.",
      "zh": "沉入长夜。"
    },
    {
      "id": "1-0",
      "file": "audio/sentences/01_00.mp3",
      "de": "Ich legte den Kasten auf den Tisch.",
      "zh": "我将木匣轻置于桌面。"
    },
    {
      "id": "1-1",
      "file": "audio/sentences/01_01.mp3",
      "de": "Ich dachte, jetzt wird alles leicht.",
      "zh": "曾以为此后万事皆安。"
    },
    {
      "id": "1-2",
      "file": "audio/sentences/01_02.mp3",
      "de": "Ich dachte, Schuld bekommt ein Ende,",
      "zh": "曾以为罪孽终会落幕，"
    },
    {
      "id": "1-3",
      "file": "audio/sentences/01_03.mp3",
      "de": "wenn man sie endlich leise Aigt.",
      "zh": "只要轻声袒露便算了结。"
    },
    {
      "id": "1-4",
      "file": "audio/sentences/01_04.mp3",
      "de": "Doch morgens war das Zimmer leer.",
      "zh": "可清晨房间空荡一片。"
    },
    {
      "id": "1-5",
      "file": "audio/sentences/01_05.mp3",
      "de": "Der Schrank war offen, kalt und weiß.",
      "zh": "柜门敞开，惨白凄寒。"
    },
    {
      "id": "1-6",
      "file": "audio/sentences/01_06.mp3",
      "de": "Ich kam zu spät, ich kam zu spät,",
      "zh": "我终究来迟，为时已晚，"
    },
    {
      "id": "1-7",
      "file": "audio/sentences/01_07.mp3",
      "de": "und Reue hat keinen Preis.",
      "zh": "悔恨早已无从标价偿还。"
    },
    {
      "id": "1-8",
      "file": "audio/sentences/01_08.mp3",
      "de": "Ich wollte heilen, was ich brach.",
      "zh": "我曾想弥补亲手击碎的过往。"
    },
    {
      "id": "1-9",
      "file": "audio/sentences/01_09.mp3",
      "de": "Ich wollte zahlen, was ich nahm.",
      "zh": "曾想偿还曾攫取的一切。"
    },
    {
      "id": "1-10",
      "file": "audio/sentences/01_10.mp3",
      "de": "Doch jeder Schritt zurück nach Hause",
      "zh": "可每一步归乡的步履，"
    },
    {
      "id": "1-11",
      "file": "audio/sentences/01_11.mp3",
      "de": "zündet eine neue Flamme an.",
      "zh": "都引燃一簇新的烈焰。"
    },
    {
      "id": "2-0",
      "file": "audio/sentences/02_00.mp3",
      "de": "Ich gab es zurück,",
      "zh": "我尽数归还，"
    },
    {
      "id": "2-1",
      "file": "audio/sentences/02_01.mp3",
      "de": "doch nichts kam zurück.",
      "zh": "却一无所获。"
    },
    {
      "id": "2-2",
      "file": "audio/sentences/02_02.mp3",
      "de": "Ein Grab, ein Blick,",
      "zh": "一座坟茔，一瞥凝望，"
    },
    {
      "id": "2-3",
      "file": "audio/sentences/02_03.mp3",
      "de": "ein stummer Fluch.",
      "zh": "一道无声诅咒。"
    },
    {
      "id": "2-4",
      "file": "audio/sentences/02_04.mp3",
      "de": "Der Faden schneidet meine Hand.",
      "zh": "丝线割破我的手掌。"
    },
    {
      "id": "2-5",
      "file": "audio/sentences/02_05.mp3",
      "de": "Er führt mich langsam durch die Stadt.",
      "zh": "牵引我缓缓穿行整座城邦。"
    },
    {
      "id": "2-6",
      "file": "audio/sentences/02_06.mp3",
      "de": "Ich suche dich, weil alles fällt.",
      "zh": "我四处寻你，只因万物崩塌。"
    },
    {
      "id": "2-7",
      "file": "audio/sentences/02_07.mp3",
      "de": "Ich suche dich, weil nichts mehr hält.",
      "zh": "我执着寻你，只因一切不再牢靠。"
    },
    {
      "id": "3-0",
      "file": "audio/sentences/03_00.mp3",
      "de": "Du findest mich, du findest mich",
      "zh": "你终将寻到我，终将寻到我"
    },
    {
      "id": "3-1",
      "file": "audio/sentences/03_01.mp3",
      "de": "in dieser hellen Dunkelheit.",
      "zh": "在这通明的幽暗之境。"
    },
    {
      "id": "3-2",
      "file": "audio/sentences/03_02.mp3",
      "de": "Ich suche dich, ich suche dich,",
      "zh": "我执着寻觅你，执着寻觅你，"
    },
    {
      "id": "3-3",
      "file": "audio/sentences/03_03.mp3",
      "de": "weil mir kein Weg nach Hause bleibt.",
      "zh": "只因我已无归途可依。"
    },
    {
      "id": "3-4",
      "file": "audio/sentences/03_04.mp3",
      "de": "Komm, komm, ich hör dein Herz.",
      "zh": "来吧，来吧，我听见你的心跳。"
    },
    {
      "id": "3-5",
      "file": "audio/sentences/03_05.mp3",
      "de": "Komm, komm, ich kenn den Schmerz.",
      "zh": "来吧，来吧，我深谙这份煎熬。"
    },
    {
      "id": "3-6",
      "file": "audio/sentences/03_06.mp3",
      "de": "Nachtserenade, zieh mich mit.",
      "zh": "夜之小夜曲，将我一同裹挟。"
    },
    {
      "id": "3-7",
      "file": "audio/sentences/03_07.mp3",
      "de": "Wir tanAn, wo die Schuld Arbricht.",
      "zh": "我们起舞于罪孽碎裂之地。"
    },
    {
      "id": "3-8",
      "file": "audio/sentences/03_08.mp3",
      "de": "Du findest mich, ich finde dich.",
      "zh": "你寻到我，我亦寻到你。"
    },
    {
      "id": "3-9",
      "file": "audio/sentences/03_09.mp3",
      "de": "Kein Morgen wäscht uns wieder rein.",
      "zh": "没有清晨能将我们洗刷清白。"
    },
    {
      "id": "3-10",
      "file": "audio/sentences/03_10.mp3",
      "de": "Du findest mich, ich finde dich.",
      "zh": "你寻到我，我亦寻到你。"
    },
    {
      "id": "3-11",
      "file": "audio/sentences/03_11.mp3",
      "de": "Wir sind zu spät, um frei zu sein.",
      "zh": "我们早已错失重获自由的时机。"
    },
    {
      "id": "4-0",
      "file": "audio/sentences/04_00.mp3",
      "de": "Ich biss das Lachen in den Mund.",
      "zh": "我将笑意死死咬在唇间。"
    },
    {
      "id": "4-1",
      "file": "audio/sentences/04_01.mp3",
      "de": "Nicht hier.",
      "zh": "不在此地。"
    },
    {
      "id": "4-2",
      "file": "audio/sentences/04_02.mp3",
      "de": "Nicht jetzt.",
      "zh": "不在此刻。"
    },
    {
      "id": "4-3",
      "file": "audio/sentences/04_03.mp3",
      "de": "Nicht vor ihnen.",
      "zh": "不在众人眼前。"
    },
    {
      "id": "4-4",
      "file": "audio/sentences/04_04.mp3",
      "de": "Der Kasten schlägt an meinen Rippen,",
      "zh": "木匣撞击着我的肋骨，"
    },
    {
      "id": "4-5",
      "file": "audio/sentences/04_05.mp3",
      "de": "so kalt, so süß, so nah bei mir.",
      "zh": "寒凉又诡甜，紧贴着我。"
    },
    {
      "id": "4-6",
      "file": "audio/sentences/04_06.mp3",
      "de": "Ich hielt ihn fest wie ein neues Herz,",
      "zh": "我紧抱着它如同新生的心脏，"
    },
    {
      "id": "4-7",
      "file": "audio/sentences/04_07.mp3",
      "de": "doch er blieb stumm und blieb verschlossen.",
      "zh": "它却缄默不语，紧锁不开。"
    },
    {
      "id": "4-8",
      "file": "audio/sentences/04_08.mp3",
      "de": "Ich jage nicht.",
      "zh": "我从不追逐。"
    },
    {
      "id": "4-9",
      "file": "audio/sentences/04_09.mp3",
      "de": "Ich warte nur.",
      "zh": "我只静静等候。"
    },
    {
      "id": "4-10",
      "file": "audio/sentences/04_10.mp3",
      "de": "Ich zähle leise deine Schritte.",
      "zh": "轻声细数你的脚步节奏。"
    },
    {
      "id": "4-11",
      "file": "audio/sentences/04_11.mp3",
      "de": "Du kommst mit Schuld in meiner Spur,",
      "zh": "你背负罪孽循着我的轨迹而来，"
    },
    {
      "id": "4-12",
      "file": "audio/sentences/04_12.mp3",
      "de": "und nennst es Wahrheit, nennst es Pflicht.",
      "zh": "还将其称作真理，视作宿命。"
    },
    {
      "id": "4-13",
      "file": "audio/sentences/04_13.mp3",
      "de": "Du bist kein Licht.",
      "zh": "你并非救赎之光。"
    },
    {
      "id": "4-14",
      "file": "audio/sentences/04_14.mp3",
      "de": "Du bist kein Trost.",
      "zh": "你并非慰藉良方。"
    },
    {
      "id": "4-15",
      "file": "audio/sentences/04_15.mp3",
      "de": "Du bist der Schlüssel in der Wunde.",
      "zh": "你是嵌在伤口里的那枚钥匙。"
    },
    {
      "id": "4-16",
      "file": "audio/sentences/04_16.mp3",
      "de": "Ich lächle nicht.",
      "zh": "我不会展露笑意。"
    },
    {
      "id": "4-17",
      "file": "audio/sentences/04_17.mp3",
      "de": "Noch nicht.",
      "zh": "此刻尚且不会。"
    },
    {
      "id": "4-18",
      "file": "audio/sentences/04_18.mp3",
      "de": "Noch nicht.",
      "zh": "永远尚且不会。"
    },
    {
      "id": "5-0",
      "file": "audio/sentences/05_00.mp3",
      "de": "Ich halte still,",
      "zh": "我静立不动，"
    },
    {
      "id": "5-1",
      "file": "audio/sentences/05_01.mp3",
      "de": "ich halte fest.",
      "zh": "坚守立场。"
    },
    {
      "id": "5-2",
      "file": "audio/sentences/05_02.mp3",
      "de": "Ich lasse dich kommen,",
      "zh": "我任由你奔赴而来，"
    },
    {
      "id": "5-3",
      "file": "audio/sentences/05_03.mp3",
      "de": "weil du kommen musst.",
      "zh": "只因你本就无处可逃。"
    },
    {
      "id": "5-4",
      "file": "audio/sentences/05_04.mp3",
      "de": "Dein Fehler trägt mein Aichen jetzt.",
      "zh": "你的过错，如今烙上我的印记。"
    },
    {
      "id": "5-5",
      "file": "audio/sentences/05_05.mp3",
      "de": "Dein Atem hängt in meiner Luft.",
      "zh": "你的气息，萦绕在我的周遭。"
    },
    {
      "id": "5-6",
      "file": "audio/sentences/05_06.mp3",
      "de": "Ich bin die Nacht, die dich erkennt.",
      "zh": "我是洞悉你的沉沉黑夜。"
    },
    {
      "id": "5-7",
      "file": "audio/sentences/05_07.mp3",
      "de": "Ich bin die Tür, die für dich brennt.",
      "zh": "我是为你燃烧的那扇门扉。"
    },
    {
      "id": "6-0",
      "file": "audio/sentences/06_00.mp3",
      "de": "Du findest mich, du findest mich",
      "zh": "你终将寻到我，终将寻到我"
    },
    {
      "id": "6-1",
      "file": "audio/sentences/06_01.mp3",
      "de": "in dieser hellen Dunkelheit.",
      "zh": "在这通明的幽暗之境。"
    },
    {
      "id": "6-2",
      "file": "audio/sentences/06_02.mp3",
      "de": "Ich suche dich, ich suche dich,",
      "zh": "我执着寻觅你，执着寻觅你，"
    },
    {
      "id": "6-3",
      "file": "audio/sentences/06_03.mp3",
      "de": "weil mir kein Weg nach Hause bleibt.",
      "zh": "只因我已无归途可依。"
    },
    {
      "id": "6-4",
      "file": "audio/sentences/06_04.mp3",
      "de": "Komm, komm, ich hör dein Herz.",
      "zh": "来吧，来吧，我听见你的心跳。"
    },
    {
      "id": "6-5",
      "file": "audio/sentences/06_05.mp3",
      "de": "Komm, komm, ich kenn den Schmerz.",
      "zh": "来吧，来吧，我深谙这份煎熬。"
    },
    {
      "id": "6-6",
      "file": "audio/sentences/06_06.mp3",
      "de": "Nachtserenade, zieh mich mit.",
      "zh": "夜之小夜曲，将我一同裹挟。"
    },
    {
      "id": "6-7",
      "file": "audio/sentences/06_07.mp3",
      "de": "Wir tanAn, wo die Schuld Arbricht.",
      "zh": "我们起舞于罪孽碎裂之地。"
    },
    {
      "id": "6-8",
      "file": "audio/sentences/06_08.mp3",
      "de": "Du findest mich, ich finde dich.",
      "zh": "你寻到我，我亦寻到你。"
    },
    {
      "id": "6-9",
      "file": "audio/sentences/06_09.mp3",
      "de": "Kein Morgen wäscht uns wieder rein.",
      "zh": "没有清晨能将我们洗刷清白。"
    },
    {
      "id": "6-10",
      "file": "audio/sentences/06_10.mp3",
      "de": "Du findest mich, ich finde dich.",
      "zh": "你寻到我，我亦寻到你。"
    },
    {
      "id": "6-11",
      "file": "audio/sentences/06_11.mp3",
      "de": "Wir sind zu spät, um frei zu sein.",
      "zh": "我们早已错失重获自由的时机。"
    },
    {
      "id": "7-0",
      "file": "audio/sentences/07_00.mp3",
      "de": "Ich halte das Aichen,",
      "zh": "我攥紧那枚印记，"
    },
    {
      "id": "7-1",
      "file": "audio/sentences/07_01.mp3",
      "de": "doch es hält mich.",
      "zh": "却反被它牢牢禁锢。"
    },
    {
      "id": "7-2",
      "file": "audio/sentences/07_02.mp3",
      "de": "Ich halte den Kasten,",
      "zh": "我守着那只木匣，"
    },
    {
      "id": "7-3",
      "file": "audio/sentences/07_03.mp3",
      "de": "doch er schließt mich.",
      "zh": "却被它彻底封锁。"
    },
    {
      "id": "7-4",
      "file": "audio/sentences/07_04.mp3",
      "de": "Ich wollte zurück.",
      "zh": "我曾渴望回头。"
    },
    {
      "id": "7-5",
      "file": "audio/sentences/07_05.mp3",
      "de": "Ich wollte es gut machen.",
      "zh": "曾想弥补一切过错。"
    },
    {
      "id": "7-6",
      "file": "audio/sentences/07_06.mp3",
      "de": "Du wolltest zurück,",
      "zh": "你一心想要回头，"
    },
    {
      "id": "7-7",
      "file": "audio/sentences/07_07.mp3",
      "de": "doch du kamst in meine Falle.",
      "zh": "却踏入了我的陷阱。"
    },
    {
      "id": "7-8",
      "file": "audio/sentences/07_08.mp3",
      "de": "Sag mir, ob noch etwas bleibt.",
      "zh": "告诉我，是否还有什么未曾消逝。"
    },
    {
      "id": "7-9",
      "file": "audio/sentences/07_09.mp3",
      "de": "Bleib still.",
      "zh": "安静待着。"
    },
    {
      "id": "7-10",
      "file": "audio/sentences/07_10.mp3",
      "de": "Ich weiß, was von dir bleibt.",
      "zh": "我清楚你最终会剩下什么。"
    },
    {
      "id": "7-11",
      "file": "audio/sentences/07_11.mp3",
      "de": "Ich habe alles zweimal verloren.",
      "zh": "我已两次失去所有一切。"
    },
    {
      "id": "7-12",
      "file": "audio/sentences/07_12.mp3",
      "de": "Dann komm.",
      "zh": "那就过来。"
    },
    {
      "id": "7-13",
      "file": "audio/sentences/07_13.mp3",
      "de": "Ich gebe dir einen Grund.",
      "zh": "我会给你一个继续的理由。"
    },
    {
      "id": "7-14",
      "file": "audio/sentences/07_14.mp3",
      "de": "Wir halten den Faden,",
      "zh": "我们紧握着丝线，"
    },
    {
      "id": "7-15",
      "file": "audio/sentences/07_15.mp3",
      "de": "doch der Faden hält uns.",
      "zh": "丝线却将我们牢牢捆绑。"
    },
    {
      "id": "7-16",
      "file": "audio/sentences/07_16.mp3",
      "de": "Wir suchen den Ausgang,",
      "zh": "我们苦苦寻找出口，"
    },
    {
      "id": "7-17",
      "file": "audio/sentences/07_17.mp3",
      "de": "doch die Nacht singt für uns.",
      "zh": "长夜却只为我们低声吟唱。"
    },
    {
      "id": "8-0",
      "file": "audio/sentences/08_00.mp3",
      "de": "Wir finden uns, wir finden uns",
      "zh": "我们终将相遇，终将相遇"
    },
    {
      "id": "8-1",
      "file": "audio/sentences/08_01.mp3",
      "de": "in dieser schönen Dunkelheit.",
      "zh": "在这绝美幽暗之境里。"
    },
    {
      "id": "8-2",
      "file": "audio/sentences/08_02.mp3",
      "de": "Du führst mich tief, ich zieh dich mit,",
      "zh": "你引我坠入深渊，我将你一同裹挟，"
    },
    {
      "id": "8-3",
      "file": "audio/sentences/08_03.mp3",
      "de": "bis keiner seinen Namen weiß.",
      "zh": "直到无人再记得彼此的姓名。"
    },
    {
      "id": "8-4",
      "file": "audio/sentences/08_04.mp3",
      "de": "Komm, komm, dein Herz ist laut.",
      "zh": "来吧，来吧，你的心跳汹涌不息。"
    },
    {
      "id": "8-5",
      "file": "audio/sentences/08_05.mp3",
      "de": "Komm, komm, die Nacht schaut zu.",
      "zh": "来吧，来吧，长夜静静注视着我们。"
    },
    {
      "id": "8-6",
      "file": "audio/sentences/08_06.mp3",
      "de": "Nachtserenade, brenn in mir.",
      "zh": "夜之小夜曲，在我心底熊熊燃烧。"
    },
    {
      "id": "8-7",
      "file": "audio/sentences/08_07.mp3",
      "de": "Ich falle nicht allein mit dir.",
      "zh": "我不会独自坠落，与你相伴沉沦。"
    },
    {
      "id": "8-8",
      "file": "audio/sentences/08_08.mp3",
      "de": "Du findest mich, ich finde dich.",
      "zh": "你寻到我，我亦寻到你。"
    },
    {
      "id": "8-9",
      "file": "audio/sentences/08_09.mp3",
      "de": "Kein Morgen macht uns wieder rein.",
      "zh": "没有清晨能将我们救赎洗白。"
    },
    {
      "id": "8-10",
      "file": "audio/sentences/08_10.mp3",
      "de": "Wir finden uns, wir binden uns.",
      "zh": "我们彼此相遇，彼此羁绊纠缠。"
    },
    {
      "id": "8-11",
      "file": "audio/sentences/08_11.mp3",
      "de": "Wir sind zu spät, um frei zu sein.",
      "zh": "我们早已错失重获自由的时机。"
    },
    {
      "id": "9-0",
      "file": "audio/sentences/09_00.mp3",
      "de": "Regen vorbei.",
      "zh": "雨已停歇。"
    },
    {
      "id": "9-1",
      "file": "audio/sentences/09_01.mp3",
      "de": "Lichter wach.",
      "zh": "灯火未眠。"
    },
    {
      "id": "9-2",
      "file": "audio/sentences/09_02.mp3",
      "de": "Ein letzter Faden",
      "zh": "最后一缕丝线"
    },
    {
      "id": "9-3",
      "file": "audio/sentences/09_03.mp3",
      "de": "in deiner Hand.",
      "zh": "握在你的掌间。"
    },
    {
      "id": "9-4",
      "file": "audio/sentences/09_04.mp3",
      "de": "Komm, komm.",
      "zh": "来吧，来吧。"
    },
    {
      "id": "9-5",
      "file": "audio/sentences/09_05.mp3",
      "de": "Nicht zurück.",
      "zh": "别再回头。"
    },
    {
      "id": "9-6",
      "file": "audio/sentences/09_06.mp3",
      "de": "Komm, komm.",
      "zh": "来吧，来吧。"
    },
    {
      "id": "9-7",
      "file": "audio/sentences/09_07.mp3",
      "de": "In die Nacht.",
      "zh": "沉入长夜。"
    }
  ]
};
